### PR TITLE
Added support for al linux usernames

### PR DESCRIPTION
**Pull request by niko9797**
Hi, nice to see how far has gone pigrow! keep up the nice job.
I like this program, i will install it as soon as i got  and if you want i am willing to help you in my free time. I created a fork where i changed all the directions of files with pi as user to the user that executes the program (to use it in distros like ubuntu mate or arch where u can select your username, and also because avoid using default usernames is a basic linux security guideline). Also in install.py i added some lines to create automatically on setup the dirloc file with system username.

As i saw you are now working in the remote control program, In future merges im thinking to help with portability for different raspberry OS. try to improve the functions and add new ones to the core program thru console and work on readmes and documentation to make more people interested in the program (to help with coding and to use it) but if you have some kind of roadmap or to do list could work in that line.

Appart from that i would like to suggest to take out the remote program from the principal repository to another one called pigrow-controller or something to sepparate clearly both programs as are independant.

Greetings, niko

### CODE REVIEW

**Comment by Pragmatismo** [comment]
oh that's really cool, i've been meaning to do that for ages thanks - i'll check it all over and pull it in asap. I've also been meaning to put the remote gui in it's own repo, just get so caught up doing other bits and pieces... I've got to work tomorrow but would be great to chat soon, i'll look over that and message you weds hopefully. thanks again, calvin.

**Comment by Pragmatismo** [comment]
thanks niko, great work!

**Comment by niko9797** [comment]
Thanks!
also more new incoming.  yesterday I tried to re structure the program specially the main install and setup scripts, I think is needed for easier future implementations and functions integration you can take a look at:
https://github.com/niko9797/Pigrow/tree/dev
Would be cool if we can chat or whatever and discuss about this changes and the future development, if u want you can mail me at niko9797@gmail.com
greetings, Niko

**Comment by Pragmatismo** [comment]
just looking at your work in progress interface, that's really cool looks great.

**Pull request merged**
